---

# `defaults read` commands fail with exit status 255 if invoked improperly, but
# 1 for non-fatal problems, such as missing values.

- name: defaults | register existing values
  command: defaults {{ item.read }}
  register: existing_defaults
  loop: '{{osx_defaults}}'
  failed_when: existing_defaults.rc > 1
  changed_when: false
  check_mode: no
  loop_control:
    label: "{{item.description}}"

- name: defaults | show existing_defaults
  debug:
    var: existing_defaults
    verbosity: 2

- name: defaults | update defaults
  command: defaults {{ item.0.write }}
  when: item.1.stdout is not search(item.0.expected)
  loop:
    '{{ osx_defaults | zip(existing_defaults.results) | list }}'
  loop_control:
    label: "{{item.0.description}}"

# Many of these settings taken (or modified) from:
#
#   https://github.com/mathiasbynens/dotfiles/blob/master/.macos
#

- name: defaults | Activity Monitor -> View -> Dock Icon -> Show CPU History
  osx_defaults: domain=com.apple.ActivityMonitor key=IconType type=int value=6

- name: defaults | Siri -> Enable Siri
  osx_defaults: domain=com.apple.assistant.support key="Assistant Enabled" type=bool value=false

- name: defaults | Don't create .DS_Store files on network volumes.
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true

- name: defaults | Don't create .DS_Store files on external USB drives.
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteUSBStores type=bool value=true

# Last tested: 10.9
- name: defaults | Automatically quit printer app once the print jobs complete
  osx_defaults: domain=com.apple.print.PrintingPrefs key="Quit When Finished" type=bool value=true

# Last tested: [10.9]
- name: defaults | Disable auto-correct
  osx_defaults: key=NSAutomaticSpellingCorrectionEnabled type=bool value=false

# Last tested: [10.9]
- name: defaults | Disable press-and-hold for keys in favor of key repeat Requires logout.
  osx_defaults: key=ApplePressAndHoldEnabled type=bool value=false

# Last tested: [10.9]
- name: defaults | Disable smart quotes, dashes, ellipses
  osx_defaults: key=NSAutomaticDashSubstitutionEnabled type=bool value=false

# Last tested: [10.9]
- name: defaults | Disable smart quotes, dashes, ellipses
  osx_defaults: key=NSAutomaticQuoteSubstitutionEnabled type=bool value=false

# Last tested: [10.9]
- name: defaults | Disable the warning when changing a file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false

# Last tested: [10.9]
- name: defaults | Don't display full POSIX path as Finder window title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool value=false

# Last tested: [10.12.6]
- name: defaults | New Finder windows show $HOME
  osx_defaults: domain=com.apple.finder key=NewWindowTarget type=string value=PfHm

# Last tested: [10.9]
- name: defaults | Expand print panel by default
  osx_defaults: key=PMPrintingExpandedStateForPrint type=bool value=true

# Last tested: [10.9]
- name: defaults | Expand print panel by default
  osx_defaults: key=PMPrintingExpandedStateForPrint2 type=bool value=true

# Last tested: [10.9]
- name: defaults | Expand save panel by default
  osx_defaults: key=NSNavPanelExpandedStateForSaveMode type=bool value=true

# Last tested: [10.9]
- name: defaults | Expand save panel by default
  osx_defaults: key=NSNavPanelExpandedStateForSaveMode2 type=bool value=true

# Last tested: [10.10.2]
- name: defaults | Finder -> Preferences -> General -> Spring-loaded folders and windows -> Delay (short)
  osx_defaults: key=com.apple.springing.delay type=float value=0

# Last tested: [10.10.2]
- name: defaults | Finder -> Preferences -> General -> Spring-loaded folders and windows
  osx_defaults: key=com.apple.springing.enabled type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> allow quitting via Command-Q; doing so will also hide desktop icons
  osx_defaults: domain=com.apple.finder key=QuitMenuItem type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> allow text selection in Quick Look
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> disable window animations and Get Info animations
  osx_defaults: domain=com.apple.finder key=DisableAllAnimations type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> show all filename extensions
  osx_defaults: key=AppleShowAllExtensions type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true

# Last tested: [10.9]
- name: defaults | Finder -> show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

- name: defaults | Finder Preferences -> New Finder windows show
  osx_defaults: domain=com.apple.finder key=NewWindowTargetPath value=file:///Users/glh/

- name: defaults | Finder Preferences -> Open folders in tabs instead of new windows
  osx_defaults: domain=com.apple.finder key=FinderSpawnTab type=bool value=false

- name: defaults | Finder Preferences -> Sidebar -> Tags -> Recent Tags
  osx_defaults: domain=com.apple.finder key=ShowRecentTags type=bool value=false

- name: defaults | Hammerspoon preferences -> Keep Console window on top
  osx_defaults: domain=org.hammerspoon.Hammerspoon key=MJKeepConsoleOnTopKey type=bool value=true

- name: defaults | Hammerspoon preferences -> Show dock icon
  osx_defaults: domain=org.hammerspoon.Hammerspoon key=MJShowDockIconKey type=bool value=false

# Last tested: [10.10.2]
- name: defaults | Make sheets drop down (almost) instantly
  osx_defaults: key=NSWindowResizeTime type=float value=0.001

# Last tested: [10.9]
- name: defaults | Require password immediately after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1

# Last tested: [10.9]
- name: defaults | Require password immediately after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=float value=0

# Last tested: 10.9
- name: defaults | Tweak subpixel font rendering (https://wincent.com/wiki/AppleFontSmoothing)
  osx_defaults: host=currentHost key=AppleFontSmoothing type=int value=1

# Last tested: [10.9]
- name: defaults | Use plain text mode for new TextEdit documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0

# Last tested: 3.1.3
- name: defaults | iTerm2 -> Preferences -> Advanced -> Windows -> Terminal windows resize smoothly
  osx_defaults: domain=com.googlecode.iterm2 key=DisableWindowSizeSnap type=bool value=true

# Last tested: 2.9.20150224-nightly
- name: defaults | iTerm2 -> Preferences -> Advanced -> Tabs -> Preferred tab width
  osx_defaults: domain=com.googlecode.iterm2 key=OptimumTabWidth type=int value=275

# Last tested: 2.9.20150224-nightly
- name: defaults | iTerm2 -> Preferences -> Appearance -> Hide scrollbars
  osx_defaults: domain=com.googlecode.iterm2 key=HideScrollbar type=bool value=true

# Last tested: 2.9.20150224-nightly
- name: defaults | iTerm2 -> Preferences -> Appearance -> Hide tab activity indicator
  osx_defaults: domain=com.googlecode.iterm2 key=HideActivityIndicator type=bool value=true

# Last tested: 3.1.3 (they still show on mouseover)
- name: defaults | iTerm2 -> Preferences -> Appearance -> Show tab close buttons
  osx_defaults: domain=com.googlecode.iterm2 key=HideTabCloseButton type=bool value=true

# Last tested: 2.9.20150224-nightly
- name: defaults | iTerm2 -> Preferences -> General -> Adjust window when changing font size
  osx_defaults: domain=com.googlecode.iterm2 key=AdjustWindowForFontSizeChange type=bool value=false

# Last tested: 3.1.3
- name: defaults | iTerm2 -> Preferences -> Appearance -> Stretch tabs to fill bar
  osx_defaults: domain=com.googlecode.iterm2 key=StretchTabsToFillBar type=bool value=true

# Last tested: 3.3.20190114-nightly (default: 1)
- name: defaults | iTerm2 -> Preferences -> Appearance -> Theme -> Dark
  osx_defaults: domain=com.googlecode.iterm2 key=TabStyleWithAutomaticOption type=int value=1

# Last tested: 3.1.3 (default: 5)
- name: defaults | iTerm2 -> Preferences -> Advanced -> General -> Width of left and right margins in terminal panes
  osx_defaults: domain=com.googlecode.iterm2 key=TerminalMargin type=int value=1

# Last tested: 3.2.20180604-nightly (default: ?)
- name: defaults | iTerm2 -> Preferences -> Advanced -> General -> Width of left and right margins in terminal panes
  osx_defaults: domain=com.googlecode.iterm2 key=TerminalVMargin type=int value=2

# Last tested: 2.9.20150224-nightly
- name: defaults | iTerm2 -> Preferences -> General -> Native full screen windows
  osx_defaults: domain=com.googlecode.iterm2 key=UseLionStyleFullscreen type=bool value=false
