---
- name: cron | schedule streamlink morning checklist 
  cron: name="morning-routine" hour="8" minute="30" job="$HOME/Documents/scripts/stream-deck/run.sh "action-checklist" "morning-checklist"
- name: cron | schedule streamlink evening checklist 
  cron: name="morning-routine" hour="18" minute="30" job="$HOME/Documents/scripts/stream-deck/run.sh "action-checklist" "evening-checklist"
